openapi: 3.0.2
info:
  description: api v1 for quan 
  version: 1.0.0
  title: Quan API
  contact:
    name: Kandakov Danil
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: Auth
    description: authentication interface
  - name: Quiz
    description: quiz interface
  - name: User
    description: user interface
paths:
  /quizzes:
    get:
      description: start quiz
      operationId: quizzes_get
      parameters:
        - in: header
          name: Access-Token
          schema:
            type: string
          required: true
          description: jwt
      tags:
        - Quiz    
      responses:
        '200':
          description: quiz started
          content:
            application/json:
              schema:
                properties:
                  quizzes:
                    type: array
                    items:
                      $ref: '#/components/schemas/quiz-body-min' 
        '400':
          description: wrong fields format
        '500':
          description: internal server error
          
  /register:
    post:
      description: craete new user
      operationId: register
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                displayname:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: user successfully created
          content:
            application/json:
              schema:
                properties:
                  uuid:
                    type: string
              example:
                uuid: uuid
        '400':
          description: wrong fields format
        '500':
          description: internal server error

  /login:
    post:
      description: login user
      operationId: login
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: username
              password: password
      responses:
        '200':
          description: user successfully logined
          content:
            application/json:
              schema:
                properties:
                  displayname:
                    type: string
                  access-token:
                    type: string
        '400':
          description: wrong fields format
        '500':
          description: internal server error

  /quiz:
    post:
      description: create new quiz
      operationId: quiz_post
      tags:
        - Quiz
      parameters:
        - in: header
          name: Access-Token
          schema:
            type: string
          description: access-token
      requestBody:
        content:
          application/json:
            schema:
              properties:
                quiz:
                  $ref: '#/components/schemas/quiz-body-create' 
      responses:
        '200':
          description: quiz created
          content:
            application/json:
              schema:
                properties:
                  access-token:
                    type: string
        '400':
          description: wrong fields format
        '500':
          description: internal server error
          
  /quiz/start/{uuid}:
    patch:
      description: start quiz
      operationId: quizstart_get
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: uuid of quiz
        - in: header
          name: Access-Token
          schema:
            type: string
          required: true
          description: jwt
      tags:
        - Quiz    
      responses:
        '200':
          description: quiz started
          content:
            application/json:
              schema:
                properties:
                  answers:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          type: string
                        answers:
                          type: array
                          items:
                            type: string
                  quiz:
                    $ref: '#/components/schemas/quiz-body' 
                  token:
                    type: string
        '400':
          description: wrong fields format
        '500':
          description: internal server error

  /quiz/{uuid}:
    get:
      description: get quiz
      operationId: quiz_get
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: uuid of quiz
        - in: header
          name: Access-Token
          schema:
            type: string
          required: true
          description: jwt
      tags:
        - Quiz
      responses:
        '200':
          description: found quiz
          content:
            application/json:
              schema:
                properties:
                  quiz:
                    $ref: '#/components/schemas/quiz-body-min'
        '400':
          description: wrong fields format
        '500':
          description: internal server error

  /quiz/{uuid}/sessions:
    get:
      description: get quiz results
      operationId: quiz_uuid_results_get
      tags:
        - User
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
        description: quiz uuid
      - in: header
        name: Access-Token
        schema:
          type: string
        required: true
        description: jwt
      - in: query
        name: session
        schema:
          type: string
        description: user
      responses:
        '200':
          description: found results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quiz-sessions-body'
        '400':
          description: wrong fields format
        '500':
          description: internal server error
  
  /quiz/session/{uuid}:
    get:
      description: get session (quiz x user)
      operationId: quiz_session_uuid_get
      tags:
        - User
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
        description: session uuid
      - in: header
        name: Access-Token
        schema:
          type: string
        required: true
        description: jwt
      - in: query
        name: session
        schema:
          type: string
        description: user
      responses:
        '200':
          description: found results
          content:
            application/json:
              schema:
                properties:
                  session: 
                    $ref: '#/components/schemas/quiz-session-body'
        '400':
          description: wrong fields format
        '500':
          description: internal server error

components:
  schemas:
    quiz-body-min:
      type: object
      properties:
        uuid:
          type: string
        owner:
          type: string
        type:
          type: integer
        title:
          type: string
        description:
          type: string
        time_limit:
          type: integer

    quiz-body-create:
      type: object
      required: [title,questions,description,type]
      properties:
        type:
          type: integer
        title:
          type: string
        description:
          type: string
        time_limit:
          type: integer
        questions:
          type: array
          items:
            $ref: '#/components/schemas/question-body-create'

    quiz-body:
      type: object
      required: [title,questions,description,type]
      properties:
        uuid:
          type: string
        owner:
          type: string
        type:
          type: integer
        title:
          type: string
        description:
          type: string
        time_limit:
          type: integer
        questions:
          type: array
          items:
            $ref: '#/components/schemas/question-body'

    question-body-create:
      type: object
      required: [title,description,type,serial,options]
      properties:
        type:
          type: integer
        title:
          type: string
        description:
          type: string
        serial:
          type: integer
        weight:
          type: integer
        options:
          type: array
          items:
            $ref: '#/components/schemas/option-body-create'

    question-body:
      type: object
      required: [title,description,type,serial,options]
      properties:
        uuid:
          type: string
        type:
          type: integer
        title:
          type: string
        description:
          type: string
        serial:
          type: integer
        options:
          type: array
          items:
            $ref: '#/components/schemas/option-body'
    
    option-body-create:
      type: object
      required: [title]
      properties:
        title:
          type: string
        serial:
          type: integer
        is_correct:
          type: boolean

    option-body:
      type: object
      required: [title]
      properties:
        uuid:
          type: string
        title:
          type: string
        serial:
          type: integer
    
    question-with-selected-answers-body:
      type: object
      properties:
        uuid:
          type: string
        type:
          type: integer
        title:
          type: string
        description:
          type: string
        serial:
          type: integer
        options:
          type: array
          items:
            type: object
            properties:
              uuid:
                type: string
              title:
                type: string
              serial:
                type: integer
              is_correct:
                type: boolean
              selected:
                type: boolean
    
    quiz-session-body:
      type: object
      properties:
        uuid:
          type: string
        user:
          type: string
        start:
          type: integer
        end:
          type: integer
        score:
          type: integer
        quiz:
          type: object
          properties:
            questions:
              type: array
              items:
                $ref: '#/components/schemas/question-with-selected-answers-body'
    
    quiz-session-body-min:
      type: object
      properties:
        uuid:
          type: string
        user:
          type: string
        start:
          type: integer
        end:
          type: integer
        score:
          type: integer
    
    quiz-sessions-body:
      type: object
      properties:
        quiz:
          $ref: '#/components/schemas/quiz-session-body-min'
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/quiz-body-min'
